[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.annuru.online

[redis]
localhost

[user]
user-dev.annuru.online

[cart]
cart-dev.annuru.online

[mysql]
localhost

[shipping]
shipping-dev.annuru.online

[rabbitmq]
localhost

[payment]
payment-dev.annuru.online

[frontend]
roboshop-dev.annuru.online